import { Fragment } from "react";
import FadeInWhenVisible from "@/components/animations/fadeInWhenVisible";

import Carousel from "@/components/carousel/carousel";
import Hero from "@/components/hero";
import Image from "next/image";

// Image array
const imageArray = [
    {
        src: "/duomo-side.jpg",
        alt: "Duomo Side",
        width: 400,
        height: 400,
        href: "https://google.com/"
    },
    {
        src: "/duomo-road.jpg",
        alt: "Duomo Road",
        width: 400,
        height: 400,
        href: "https://youtube.com/"
    },
    {
        src: "/milan.jpg",
        alt: "Milan City Centre",
        width: 400,
        height: 400,
        href: "https://bing.com/"
    }
];

export default function Home() {
    return (
        <Fragment>
            <Hero flex="flex-col" imgurl="/studying-girl.webp">
                <FadeInWhenVisible>
                <h1 className="text-4xl lg:text-8xl text-base-200">Hello There!</h1>
                <p className="text-center text-base-200">Welcome back</p>
                </FadeInWhenVisible>
            </Hero>
            <Hero
                className="px-1 md:px-3 lg:px-5 py-1 md:py-3 lg:py-5 bg-gradient-to-br from-pink-600 from-10% to-slate-950 to-90% h-[48rem]"
            >
                <Image
                    alt="some picture"
                    src="/milan.jpg"
                    width={500}
                    height={500}
                    className="rounded-lg shadow-2xl"
                />
                <FadeInWhenVisible>
                    <h1 className="text-5xl font-bold text-right text-base-200">About</h1>
                    <p className="py-6 text-right text-base-200">
                        I am a passionate 4th year computer science student at the University of Warwick,
                        exploring the realms of technology and innovation. By exploring, I mean trying out
                        new stuff which I find interesting. As you can probably already tell, the first sentence
                        was generated by ChatGPT.
                    </p>
                </FadeInWhenVisible>
            </Hero>
            <Hero
                className="px-1 md:px-3 lg:px-5 py-1 md:py-3 lg:py-5 bg-gradient-to-bl from-teal-500 from-10% to-slate-950 to-90% h-[48rem]"
            >
                <FadeInWhenVisible>
                    <h1 className="text-5xl font-bold text-base-200">Content</h1>
                    <p className="py-6 text-base-200">
                        I post my personal projects and notes here. 
                        I experiment with different frontend and backend features here as well.
                    </p>
                </FadeInWhenVisible>
                <Image
                    alt="some picture"
                    src="/milan.jpg"
                    width={500}
                    height={500}
                    className="rounded-lg shadow-2xl"
                />
            </Hero>
            <Hero
                flex="flex-col"
                className="px-1 md:px-3 lg:px-5 py-1 md:py-3 lg:py-5 bg-gradient-to-br from-cyan-400 from-10% to-slate-950 to-90% h-[48rem]"
            >
                <FadeInWhenVisible>
                    <h1 className="text-5xl font-bold text-center text-base-200">Where to begin?</h1>
                    <p className="py-6 text-base-200">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
                </FadeInWhenVisible>
                <Carousel isLinked={true} height="h-96" carouselItems={imageArray} />
            </Hero>
        </Fragment>
    );
};